config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :ideas do
    get "delete", to: 'ideas#delete'
  end

  root to: "ideas#index"

  resources :users
  resources :projects
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'edit_profile', to: 'devise/registrations#edit'
    get 'sign_out', to: 'devise/sessions#destroy'
  end
  get 'tags/:tag', to: 'ideas#index', as: "tag"

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  validates :description, presence: true

  def all_tags=(names)
    self.tags = names.split(",").uniq.map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).uniq.join(", ")
  end

  def self.tagged_with(userid, name)
    Tag.find_by_name!(name).ideas.where("user_id = ?", userid)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      if params[:tag]
        @ideas = Idea.select("ideas.id, ideas.description, ideas.created_at").tagged_with(current_user.id, params[:tag]).group("ideas.id, ideas.description, ideas.created_at")
        #@ideas.map do |i|
        #  puts i.description
        #end
      else
        @ideas = current_user.ideas
      end
    end
  end

  def show
  end

  def new
    @idea = Idea.new
  end

  def create
    puts params[:all_tags]
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        #redirect_to ideas_path
        format.js
      else
        #render "new"
        format.html { render root_path }
      end
    end
  end

  def edit
  end

  def update
    @idea.update_attributes(idea_params)

    if @idea.errors.empty?
      redirect_to root_path
    end
  end

  def delete
    @idea = Idea.find(params[:idea_id])
  end

  def destroy
    @idea.destroy
    redirect_to root_path
  end

  private

  def idea_params
    params.require(:idea).permit(:description, :user_id, :all_tags)
  end

  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end

  def tag_cloud(tags, classes, userid)
    ideas = Idea.where("user_id = ?", userid)
    idea_ids = []
    ideas.map do |i|
      idea_ids << i.id
    end
    #user_tags = Tagging.select("tag_id").where(idea_id: idea_ids)

    user_tags = Tag.counts.group("tags.name").where("taggings.idea_id": idea_ids)

    max = user_tags.sort_by(&:count).last

    user_tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/ideas/_delete.html.slim
div class="modal-dialog"
  div class="modal-content"
    div class="modal-header"
      h3 Удалить идею

    div class="modal-body"
      ul class="errors"
      p Вы действительно хотите удалить данную идею?

    div class="modal-footer"
      = link_to "Да, удалить данную идею", idea_path(@idea), method: :delete, remote: true, class: "btn btn-danger"
      = link_to "Нет, не надо", "#", class: "btn btn-default", data: { dismiss: "modal" }

app/views/ideas/_edit.html.slim
div class="modal-header"
  h3 = "Редактировать #{@idea.description}"
= render "form"

app/views/ideas/_form.html.slim
div class="modal-dialog"
  div class="modal-content"
    = form_for @idea, remote: true, html: { style: "display:inline;" } do |f|
      div class="modal-body"
        ul class="errors"

        div class="form-group"
          = f.label :description, class:"control-label"
          = f.text_area :description, class: "form-control"

      div class="modal-footer"
        = f.submit class: "btn btn-primary"
        = link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"}

app/views/ideas/_idea.html.slim
= div_for idea, class: "well" do
  div class="pull-right"
    sup = "From " + time_ago_in_words(idea.created_at)
    = link_to idea_path(idea), method: :delete do
      span class="glyphicon glyphicon-trash"
  br
  = idea.description
  hr
  = raw tag_links(idea.all_tags)

app/views/ideas/_new.html.slim
= form_for(Idea.new, remote: true) do |f|
  = f.text_area :description, placeholder: "Ваша идея", rows: 5, class: "form-control"
  br
  = f.text_field :all_tags, placeholder: "Тэги через запятую", class: "form-control"
  = f.hidden_field :user_id, value: current_user.id
  br
  = f.submit "Отправить", class: "btn btn-default btn-block"

app/views/ideas/create.js.erb
var new_idea = $("<%= escape_javascript(render(partial: @idea))%>").hide();
$('#ideas').prepend(new_idea);
$('#idea_<%= @idea.id %>').fadeIn('slow');
$('#new_idea')[0].reset();

app/views/ideas/delete.js.erb
$("#idea-modal").html("<%= escape_javascript(render 'delete') %>")
$("#idea-modal").modal("show")

app/views/ideas/destroy.js.erb
$("#idea-modal").modal("hide")

app/views/ideas/edit.js.erb
$("#idea-modal").html("<%= escape_javascript(render 'edit') %>")
$("#idea-modal").modal("show")

app/views/ideas/index.html.slim
- if user_signed_in?
  div class="container"
    div class="col-md-6"
      = render partial: "ideas/new"

      h4 Облако тэгов
      - tag_cloud Tag.counts.group("tags.name"), %w{tag-xs tag-sm tag-md tag-lg}, current_user.id do |tag, css_class|
        = link_to tag.name, tag_path(tag.name), class: css_class
        | &nbsp;
    div class="col-md-6"
      div id="ideas"
        = render partial: @ideas.reverse
  div id="idea-modal" class="modal fade"
- else
  div class="container"
    div class="jumbotron"
      h1 = "Генератор идей"
      p = "Данное приложение поможет вам постоянно тренировать мозг, на предмет генерации идей все, что вам нужно - это ежедневно придумывать идеи, пусть самые нелепые"
      p = "Также данное приложение поможет вам систематизировать ваши идеи, группируя их, вы всегда сможете вернуться к проблемам, или проектам, для которых вы придумывали данные идеи"
      p = "Попробуйте наше приложение, все, что вам нужно это войти под своим логином, или зарегистрироваться"
      /= link_to "Sign up", sign_up_path, class: "btn btn-lg btn-primary"

app/views/ideas/new.html.slim
h2 = t :add_idea
.row
  .col-md-5
  .col-md-2
    = form_for(@idea) do |f|
      = f.label (t :add_idea)
      = f.text_area :description, class: "form-control"
      = f.hidden_field :user_id, value: current_user.id
      br
      = f.submit (t :idea_create), class: "btn btn-default btn-block"

app/views/ideas/show.html.slim
h2 = t :add_idea
.row
  .col-md-5
  .col-md-2
    = form_for(@idea) do |f|
      = f.label (t :add_idea)
      = f.text_area :description, class: "form-control"

app/views/ideas/update.js.erb
$("#idea-modal").modal("hide")