config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :ideas do
    get "delete", to: 'ideas#delete'
  end

  root to: "ideas#index"

  resources :users
  resources :projects
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'edit_profile', to: 'devise/registrations#edit'
    get 'sign_out', to: 'devise/sessions#destroy'
  end
  get 'tags/:tag', to: 'ideas#index', as: "tag"

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_many :ideas
    belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)

    if @project.save
      redirect_to projects_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @project.update_attributes(project_params)

    if @project.errors.empty?
      redirect_to @project
    else
      render "edit"
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :descrition, :user_id)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<%= f.label :title, (t :your_project_title) %>
<%= f.text_field_tag :title, as: :string, :required => false %>
<%= f.label :descrition, (t :your_project_description) %>
<%= f.text_field_tag :descrition, as: :string, :required => false %>

app/views/projects/edit.html.slim
h2 = t :edit_project
.row
  .col-md-4
  .col-md-4
    = form_for(@project) do |f|
      = f.label (t :your_project_title)
      = f.text_field :title, class: "form-control"
      br
      = f.label (t :your_project_description)
      = f.text_area :descrition, class: "form-control"
      = f.hidden_field :user_id, value: current_user.id
      br
      = f.submit (t :edit_project), class: "btn btn-default btn-block"

app/views/projects/index.html.slim
h2 = t :list_project
.row
  .col-md-2
  .col-md-8
    table class="table table-striped table-bordered"
      tr
        th = t :your_project_title
        th = t :your_project_description
        th = t :actions
        - @projects.each do |project|
          tr
            td = project.title
            td = project.descrition
            td
              div class="btn-group"
                = link_to (t :show), project_path(project), class: "btn btn-default btn-xs"
                = link_to (t :edit), edit_project_path(project), class: "btn btn-default btn-xs"
                = link_to (t :delete), project_path(project), method: :delete, data: { confirm: (t :confirm_del) }, class: "btn btn-default btn-xs"

app/views/projects/new.html.slim
h2 = t :add_project
.row
  .col-md-4
  .col-md-4
    = form_for(@project) do |f|
      = f.label (t :your_project_title)
      = f.text_field :title, class: "form-control"
      br
      = f.label (t :your_project_description)
      = f.text_area :descrition, class: "form-control"
      = f.hidden_field :user_id, value: current_user.id
      br
      = f.submit (t :projects_create), class: "btn btn-default btn-block"

app/views/projects/show.html.slim
h2 = t :your_project_title
.row
  .col-md-4
  .col-md-4
    = form_for(@project) do |f|
      = f.label (t :your_project_title)
      = f.text_field :title, class: "form-control"
      br
      = f.label (t :your_project_description)
      = f.text_area :descrition, class: "form-control"