config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :ideas do
    get "delete", to: 'ideas#delete'
  end

  root to: "ideas#index"

  resources :users
  resources :projects
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'edit_profile', to: 'devise/registrations#edit'
    get 'sign_out', to: 'devise/sessions#destroy'
  end
  get 'tags/:tag', to: 'ideas#index', as: "tag"

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/swagger'

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Idea Machine
    meta name="keywords" content="template language"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav class="navbar navbar-inverse navbar-fixed-top"
      div class="container"
        div class="navbar-header"
          = link_to "IDEA MACHINE", root_path, class: "navbar-brand"

        div id="navbar" class="navbar-collapse collapse"
          ul class="nav navbar-nav navbar-right"
            li = link_to "Home", root_path
            - if user_signed_in?
              li = link_to "Profile", edit_profile_path
              li = link_to "Log out", sign_out_path
            - else
              li = link_to "Sign in", sign_in_path
              li = link_to "Sign up", sign_up_path
    == yield